<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>com.github.zengfr</groupId>
    <artifactId>easymodbus4j-root</artifactId>
    <version>0.0.5</version>
    <packaging>pom</packaging>
    <name>easymodbus4j-root</name>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <modules>
        <module>easymodbus4j-extension</module>
        <module>easymodbus4j-commandclient</module>
    </modules>
</project>
